# Skip builds for new tags.
if: tag IS blank

# Only build on the following branches.
branches:
  only:
    - master
    - develop

# Use Python as the base image/language.
language: python
python:
  - "2.7"

# Sudo and Docker both required for the build.
sudo: required
services:
  - docker

# Commands to run before the testing.
before_script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose run --rm -T app yarn install
  - docker-compose run --rm -T app mv .env.example .env

# Commands to run for the tests.
script:
  - docker-compose run --rm -T -e CI=true app yarn run test -- --passWithNoTests

# Commands to run before deploying.
before_deploy:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

# Commands to run for deploying.
deploy:
  - provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
